### ISSUE TITLE
requesting names of marks on the same chat line

### ISSUE THREAD

**Issue by godislobster** [wexxlee/conductor-helper#1]
Hi!

So yes, I want the names of the marks on the same chat line as their coordinates. I am still all hands finding which one is which and at least for lumi, because she gets a special shout out, it can get annoying to figure out where I am going, especially if I don't have the current scout maps up and my hands and anxiety get in the way.

Dakota!

**Comment by wexxlee** [comment]
> Hi!
> 
> So yes, I want the names of the marks on the same chat line as their coordinates. I am still all hands finding which one is which and at least for lumi, because she gets a special shout out, it can get annoying to figure out where I am going, especially if I don't have the current scout maps up and my hands and anxiety get in the way.
> 
> Dakota!

Hey Dakota!

It's a little tricky, because it's technically the `ChatCoordinates` plugin that's echoing the flag to you (from the `/coord` command), and the plugin doesn't currently have the capability to add a comment before or after the flag (e.g., the mark name).

One idea that could work is if I provide an option to manually echo the flag with `/echo` **after** `/coord` sets the flag.  The downside is the macros would get a little longer, since each mark would require two lines (`/coord (whatever)` to set the flag, then `/echo MarkName: <flag>` to put it in your echo log.  But not that big a deal since they only need to be run one.  There's also  setting that will prevent `/coord` from echoing the flag itself, so you wouldn't have to worry about duplicate flags in your battle log.

Let me play around and mock up a prototype!

**Comment by wexxlee** [comment]
> Hi!
> 
> So yes, I want the names of the marks on the same chat line as their coordinates. I am still all hands finding which one is which and at least for lumi, because she gets a special shout out, it can get annoying to figure out where I am going, especially if I don't have the current scout maps up and my hands and anxiety get in the way.
> 
> Dakota!

OK - new version of the tool is live with an `Echo mark names with flags` option -- take a look and let me know what you think!
